-- One-time job publication payments.
-- This file does not INSERT, UPDATE, or DELETE any existing job.
-- Apply it separately. It is not applied by the application deploy.
--
-- Activation remains blocked for every role unless this transaction
-- was opened by public.publish_paid_job for that exact job id.
-- The setting is transaction-local and is not a client parameter.

CREATE TABLE public.job_publication_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  job_id bigint NOT NULL,
  user_id uuid NOT NULL,
  plan text NOT NULL,
  amount numeric(10,2) NOT NULL,
  currency text NOT NULL,
  stripe_checkout_session_id text NOT NULL,
  stripe_event_id text NOT NULL,
  status text NOT NULL,
  paid_at timestamptz,
  CONSTRAINT job_publication_payments_currency_check
    CHECK (currency = 'EUR'),
  CONSTRAINT job_publication_payments_status_check
    CHECK (status = 'paid'),
  CONSTRAINT job_publication_payments_plan_amount_check
    CHECK (
      (plan = 'Basic' AND amount = 9.99)
      OR (plan = 'Professional' AND amount = 19.99)
      OR (plan = 'Business' AND amount = 39.99)
    ),
  CONSTRAINT job_publication_payments_session_key
    UNIQUE (stripe_checkout_session_id),
  CONSTRAINT job_publication_payments_event_key
    UNIQUE (stripe_event_id),
  CONSTRAINT job_publication_payments_job_id_fkey
    FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE,
  CONSTRAINT job_publication_payments_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX job_publication_payments_one_paid_job
  ON public.job_publication_payments (job_id);

CREATE INDEX job_publication_payments_user_idx
  ON public.job_publication_payments (user_id);

ALTER TABLE public.job_publication_payments ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.job_publication_payments
  FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT ON TABLE public.job_publication_payments
  TO service_role;

REVOKE ALL ON SEQUENCE public.job_publication_payments_id_seq
  FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.enforce_job_publication_status()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  IF current_user = 'anon' THEN
    RAISE EXCEPTION 'anonymous users cannot create or change jobs'
      USING ERRCODE = '42501';
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.status IS NULL THEN
      NEW.status := 'pending_payment';
    END IF;

    IF NEW.status IS NOT DISTINCT FROM 'active' THEN
      RAISE EXCEPTION 'jobs cannot be created as active before payment verification'
        USING ERRCODE = '42501';
    END IF;

    IF current_user = 'authenticated'
       AND NEW.user_id IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'jobs can only be created for the current user'
        USING ERRCODE = '42501';
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF NEW.user_id IS DISTINCT FROM OLD.user_id THEN
      RAISE EXCEPTION 'job owner cannot be reassigned'
        USING ERRCODE = '42501';
    END IF;

    IF current_user = 'authenticated'
       AND OLD.user_id IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'users cannot change another user job'
        USING ERRCODE = '42501';
    END IF;

    IF NEW.status IS NOT DISTINCT FROM 'active'
       AND OLD.status IS DISTINCT FROM 'active'
       AND pg_catalog.current_setting('havkar.job_publication_job_id', true)
         IS DISTINCT FROM NEW.id::text THEN
      RAISE EXCEPTION 'unpaid jobs cannot become active until a verified publication payment is recorded'
        USING ERRCODE = '42501';
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    IF current_user = 'authenticated'
       AND OLD.user_id IS DISTINCT FROM auth.uid() THEN
      RAISE EXCEPTION 'users cannot delete another user job'
        USING ERRCODE = '42501';
    END IF;

    RETURN OLD;
  END IF;

  RAISE EXCEPTION 'enforce_job_publication_status is a trigger function'
    USING ERRCODE = '0A000';
END;
$$;

REVOKE ALL ON FUNCTION public.enforce_job_publication_status()
  FROM PUBLIC, anon, authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.enforce_job_publication_status()
  TO service_role;

CREATE OR REPLACE FUNCTION public.publish_paid_job(
  p_job_id bigint,
  p_user_id uuid,
  p_plan text,
  p_amount numeric,
  p_currency text,
  p_checkout_session_id text,
  p_event_id text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_job public.jobs%ROWTYPE;
  v_existing public.job_publication_payments%ROWTYPE;
  v_updated integer;
BEGIN
  IF p_checkout_session_id IS NULL
     OR btrim(p_checkout_session_id) = ''
     OR p_event_id IS NULL
     OR btrim(p_event_id) = ''
     OR p_checkout_session_id NOT LIKE 'cs_%'
     OR p_event_id NOT LIKE 'evt_%' THEN
    RAISE EXCEPTION 'missing stripe reference'
      USING ERRCODE = '22023';
  END IF;

  IF p_currency IS DISTINCT FROM 'EUR' THEN
    RAISE EXCEPTION 'unsupported publication currency'
      USING ERRCODE = '22023';
  END IF;

  IF NOT (
    (p_plan = 'Basic' AND p_amount = 9.99)
    OR (p_plan = 'Professional' AND p_amount = 19.99)
    OR (p_plan = 'Business' AND p_amount = 39.99)
  ) THEN
    RAISE EXCEPTION 'unknown job plan price'
      USING ERRCODE = '22023';
  END IF;

  SELECT *
    INTO v_existing
  FROM public.job_publication_payments
  WHERE stripe_checkout_session_id = p_checkout_session_id
     OR stripe_event_id = p_event_id
  FOR UPDATE;

  IF FOUND THEN
    IF v_existing.job_id = p_job_id
       AND v_existing.user_id = p_user_id
       AND v_existing.stripe_checkout_session_id = p_checkout_session_id
       AND v_existing.stripe_event_id = p_event_id
       AND v_existing.status = 'paid' THEN
      RETURN 'duplicate';
    END IF;

    RAISE EXCEPTION 'stripe reference already used'
      USING ERRCODE = '23505';
  END IF;

  SELECT *
    INTO v_job
  FROM public.jobs
  WHERE id = p_job_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'job not found'
      USING ERRCODE = 'P0002';
  END IF;

  IF v_job.status = 'active' THEN
    RETURN 'already_active';
  END IF;

  IF v_job.user_id IS DISTINCT FROM p_user_id
     OR v_job.plan IS DISTINCT FROM p_plan
     OR v_job.monthly_fee IS DISTINCT FROM p_amount
     OR v_job.status IS DISTINCT FROM 'pending_payment' THEN
    RAISE EXCEPTION 'job is not payable'
      USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.job_publication_payments (
    job_id,
    user_id,
    plan,
    amount,
    currency,
    stripe_checkout_session_id,
    stripe_event_id,
    status,
    paid_at
  ) VALUES (
    p_job_id,
    p_user_id,
    p_plan,
    p_amount,
    p_currency,
    p_checkout_session_id,
    p_event_id,
    'paid',
    pg_catalog.now()
  );

  PERFORM pg_catalog.set_config(
    'havkar.job_publication_job_id',
    p_job_id::text,
    true
  );

  UPDATE public.jobs
  SET status = 'active'
  WHERE id = p_job_id
    AND user_id = p_user_id
    AND status = 'pending_payment'
    AND plan = p_plan
    AND monthly_fee IS NOT DISTINCT FROM p_amount;

  GET DIAGNOSTICS v_updated = ROW_COUNT;

  IF v_updated <> 1 THEN
    RAISE EXCEPTION 'job publication did not update one row'
      USING ERRCODE = '40001';
  END IF;

  RETURN 'published';
END;
$$;

REVOKE ALL ON FUNCTION public.publish_paid_job(bigint, uuid, text, numeric, text, text, text)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.publish_paid_job(bigint, uuid, text, numeric, text, text, text)
  TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_trigger
    WHERE tgname = 'enforce_job_publication_status'
      AND tgrelid = 'public.jobs'::regclass
      AND NOT tgisinternal
  ) THEN
    RAISE EXCEPTION 'enforce_job_publication_status trigger is missing'
      USING ERRCODE = '42704';
  END IF;
END;
$$;
